{{- range $key, $val := $.Values.projects }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $key }}
  namespace: {{ $.Values.argocdNamespace | default "openshift-gitops" }}
spec:
  description: '{{ $key }} Project'
{{- range $repo := $val.sources }}
  sourceRepos:
    - '{{ $repo }}'
{{- end }}
  destinations:
{{- range $ns := $val.destinationsNamespaces }}
    - namespace: {{ $ns }}
      server: https://kubernetes.default.svc
{{- end }}  
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admins
      description: 'Admins for {{ $key }} project'
      policies:
        - 'p, proj:{{ $key }}:admins, applications, *, *, allow'
        - 'p, proj:{{ $key }}:admins, applicationsets, *, *, allow'
        - 'p, proj:{{ $key }}:admins, repositories, *, *, allow'
        - 'p, proj:{{ $key }}:admins, certificates, *, *, allow'
{{ if $val.groupsAdmins }}
      groups:
{{- range $admin := $val.groupsAdmins }}
        - {{ $admin }}
{{- range $user := $val.usersAdmins }}
        - {{ $user }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}