apiVersion: v2
name: external-secrets
description: A Helm chart to manage secrets in Openshift using External Secrets Operator
type: application

version: 0.1.0
appVersion: 0.1.16

mantainers:
  - name: Asier Cidon
    email: acidonpe@redhat.com
