apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: openshift-gitops
spec:
  destination:
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  source:
    path: './charts/external-secrets'
    repoURL: 'https://github.com/acidonper/ocp-gitops-adm.git'
    targetRevision: HEAD
    helm:
      valueFiles:
        - '../../values/cluster-lab/values-external-secrets.yaml'
  sources: []
  project: 'default'
  syncPolicy:
    automated:
      enabled: true