{{- range  $.Values.rbac.cluster.admins.users }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusteradmin-{{ . }}
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: {{ . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
{{- end }}
