{{- range $key, $val := $.Values.namespaces }}
{{- range $val.admins.users }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admins-ns-{{ . }}
  namespace: {{ $key }}
subjects:
  - kind: User
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
{{- end }}
{{- end }}
