apiVersion: v2
name: operators
description: A Helm chart to install operators in Openshift
type: application

version: 0.1.0
appVersion: 0.1.16

mantainers:
  - name: Asier Cidon
    email: acidonpe@redhat.com
